name: ci

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: hello0zaizai
        uses: docker/login-action@v3
        with:
          username: hello0zaizai
          password: dckr_pat_5efqbkAlzyxydOAV2-DSK7odIp0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ github.event.repository.name }}:latest
